#!/usr/bin/env python3
"""
Standalone GPT-2 generation on ANE — zero coremltools.

Pipeline: model_loader.py → compiler.py → .mlmodelc → ane_standalone_pipe → ANE

Every .mlmodelc generated by OUR compiler (compiler.py).
Every .hwx produced is byte-identical to what our emitter generates (proven Gate 1).
aned is used only as a loader — the binary content is determined by our compiler.
Dispatch via doEvaluateDirectWithModel (guaranteed ANE).

Zero coremltools. Zero external ML framework. Our compiler, our dispatch.

Copyright 2026 Nick Lo. MIT License.
"""

import os, sys, time, subprocess, struct, json
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
from compiler import gen_conv_mlmodelc, gen_softmax_mlmodelc, gen_layernorm_mlmodelc, generate_mlmodelc
from model_loader import GPT2Model
from kv_cache import KVCache

MODEL_PATH = os.path.expanduser(
    "~/.cache/huggingface/hub/models--openai-community--gpt2/"
    "snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e/model.safetensors")
PIPE_TOOL = os.path.join(os.path.dirname(__file__), 'tests', 'ane_standalone_pipe')
BUILD_DIR = '/tmp/gpt2_standalone_gen'


def layernorm_cpu(x, weight, bias, eps=1e-5):
    x32 = x.astype(np.float32)
    m = x32.mean()
    v = ((x32 - m) ** 2).mean()
    return ((x32 - m) / np.sqrt(v + eps) * weight.astype(np.float32)
            + bias.astype(np.float32)).astype(np.float16)


def gelu_new_cpu(x):
    x32 = x.astype(np.float32)
    return (0.5 * x32 * (1 + np.tanh(np.sqrt(2/np.pi) * (x32 + 0.044715 * x32**3)))).astype(np.float16)


def softmax_cpu(x):
    x32 = x.astype(np.float32)
    e = np.exp(x32 - x32.max())
    return (e / e.sum()).astype(np.float16)


def embed(model, token_id, pos):
    return (model.wte[token_id].astype(np.float32) +
            model.wpe[pos].astype(np.float32)).astype(np.float16)


class StandaloneDispatcher:
    """Persistent pipe dispatch using only our compiler output."""

    def __init__(self, model, build_dir):
        self.model = model
        self.build_dir = build_dir
        self.config = model.config
        os.makedirs(build_dir, exist_ok=True)
        self._ops = {}  # name → (mlmodelc_path, in_ch, out_ch)
        self._op_list = []  # ordered list for manifest
        self._proc = None
        self._idx_map = {}  # name → manifest index

    def compile_all(self):
        """Generate all .mlmodelc via OUR compiler (zero coremltools)."""
        dim = self.config.n_embd
        ffn = self.config.n_inner
        vocab = self.config.vocab_size

        for i in range(self.config.n_layer):
            L = self.model.layers[i]
            layer_dir = os.path.join(self.build_dir, f'L{i}')
            os.makedirs(layer_dir, exist_ok=True)

            # Projections with fused bias (our compiler handles bias natively)
            for name, W, b in [
                (f'L{i}_v', L.W_v, L.bias_v),
                (f'L{i}_o', L.W_o, L.c_proj_bias),
            ]:
                mlc = os.path.join(layer_dir, f'{name.split("_")[1]}.mlmodelc')
                if not os.path.exists(mlc):
                    gen_conv_mlmodelc(mlc, W.astype(np.float32), dim, dim,
                                      bias=b.astype(np.float32))
                self._ops[name] = (mlc, dim, dim)

            # FFN up + bias
            mlc_up = os.path.join(layer_dir, 'fc_up.mlmodelc')
            if not os.path.exists(mlc_up):
                gen_conv_mlmodelc(mlc_up, L.W_fc.astype(np.float32), dim, ffn,
                                  bias=L.c_fc_bias.astype(np.float32))
            self._ops[f'L{i}_fc_up'] = (mlc_up, dim, ffn)

            # FFN down + bias
            mlc_dn = os.path.join(layer_dir, 'fc_dn.mlmodelc')
            if not os.path.exists(mlc_dn):
                gen_conv_mlmodelc(mlc_dn, L.W_fc_down.astype(np.float32), ffn, dim,
                                  bias=L.c_proj_ffn_bias.astype(np.float32))
            self._ops[f'L{i}_fc_dn'] = (mlc_dn, ffn, dim)

        # lm_head (no bias, tied to embedding)
        mlc_lm = os.path.join(self.build_dir, 'lm_head.mlmodelc')
        if not os.path.exists(mlc_lm):
            gen_conv_mlmodelc(mlc_lm, self.model.wte.astype(np.float32), dim, vocab)
        self._ops['lm_head'] = (mlc_lm, dim, vocab)

        # Build ordered list + manifest
        self._op_list = sorted(self._ops.keys())
        self._idx_map = {name: i for i, name in enumerate(self._op_list)}

        manifest = os.path.join(self.build_dir, 'manifest.txt')
        with open(manifest, 'w') as f:
            for name in self._op_list:
                mlc, ic, oc = self._ops[name]
                f.write(f"{mlc} {ic} {oc}\n")

        return manifest

    def start(self, manifest):
        """Launch pipe tool, compile all models, enter dispatch loop."""
        self._proc = subprocess.Popen(
            [PIPE_TOOL, manifest],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        while True:
            line = self._proc.stdout.readline().decode().strip()
            if line == 'READY_FOR_SWAP':
                break
            if self._proc.poll() is not None:
                raise RuntimeError(f"Pipe died: {self._proc.stderr.read().decode()}")

        self._proc.stdin.write(b"GO\n")
        self._proc.stdin.flush()

    def dispatch(self, name, input_fp16):
        idx = self._idx_map[name]
        _, ic, oc = self._ops[name]
        cmd = f"D {idx}\n".encode()
        self._proc.stdin.write(cmd)
        self._proc.stdin.write(input_fp16.astype(np.float16).tobytes())
        self._proc.stdin.flush()
        out = self._proc.stdout.read(oc * 2)
        return np.frombuffer(out, dtype=np.float16).copy()

    def stop(self):
        if self._proc:
            self._proc.stdin.write(b"Q\n")
            self._proc.stdin.flush()
            self._proc.wait(timeout=5)


def forward_layer_decode(layer_idx, x, model, disp, kv_cache):
    L = model.layers[layer_idx]
    config = model.config
    pfx = f'L{layer_idx}'

    # LayerNorm 1 (CPU)
    ln1 = layernorm_cpu(x, L.ln_1_weight, L.ln_1_bias, config.layer_norm_epsilon)

    # Q/K/V projections (ANE, fused bias)
    q = disp.dispatch(f'{pfx}_v', ln1)  # reuse v_proj for Q temporarily
    # Actually need separate Q/K/V. For now: Q=K=V share v_proj (wrong but testing pipe)
    # TODO: add Q/K projections to the op set

    # For seq_len=1 first token: attention = V_proj → O_proj
    # For decode: need real Q/K/V + attention
    # Simplification: use the same architecture as generate.py (CPU attention)

    # V projection
    v = disp.dispatch(f'{pfx}_v', ln1)
    k_new = (L.W_k.astype(np.float16) @ ln1 + L.bias_k.astype(np.float16)).astype(np.float16)
    v_new = v.copy()
    q_new = (L.W_q.astype(np.float16) @ ln1 + L.bias_q.astype(np.float16)).astype(np.float16)

    # Reshape and cache
    q_heads = q_new.reshape(config.n_head, config.head_dim)
    k_heads = k_new.reshape(config.n_head, config.head_dim)
    v_heads = v_new.reshape(config.n_head, config.head_dim)
    kv_cache.append(layer_idx, k_heads[np.newaxis], v_heads[np.newaxis])
    cached_k, cached_v = kv_cache.get(layer_idx)

    # Attention on CPU
    attn_out = np.zeros(config.n_embd, dtype=np.float16)
    for h in range(config.n_head):
        q_h = q_heads[h].astype(np.float32)
        k_h = cached_k[:, h, :].astype(np.float32)
        v_h = cached_v[:, h, :].astype(np.float32)
        scores = (q_h @ k_h.T) / np.sqrt(config.head_dim)
        weights = np.exp(scores - scores.max())
        weights /= weights.sum()
        attn_out[h*config.head_dim:(h+1)*config.head_dim] = (weights @ v_h).astype(np.float16)

    # O projection (ANE)
    o = disp.dispatch(f'{pfx}_o', attn_out)

    # Residual 1
    r1 = (x.astype(np.float32) + o.astype(np.float32)).astype(np.float16)

    # LayerNorm 2 (CPU)
    ln2 = layernorm_cpu(r1, L.ln_2_weight, L.ln_2_bias, config.layer_norm_epsilon)

    # FFN (ANE: fc_up+bias, CPU: GELU, ANE: fc_down+bias)
    fc_up = disp.dispatch(f'{pfx}_fc_up', ln2)
    gelu_out = gelu_new_cpu(fc_up)
    fc_down = disp.dispatch(f'{pfx}_fc_dn', gelu_out)

    # Residual 2
    return (r1.astype(np.float32) + fc_down.astype(np.float32)).astype(np.float16)


def generate(model, disp, prompt_tokens, max_new_tokens=10):
    config = model.config
    kv_cache = KVCache(config.n_layer, config.n_head, config.head_dim)
    generated = list(prompt_tokens)

    # Prefill
    for pos, tok in enumerate(prompt_tokens):
        x = embed(model, tok, pos)
        for i in range(config.n_layer):
            x = forward_layer_decode(i, x, model, disp, kv_cache)

    logits = disp.dispatch('lm_head', layernorm_cpu(x, model.ln_f_weight, model.ln_f_bias, config.layer_norm_epsilon))
    next_tok = int(np.argmax(logits.astype(np.float32)))
    generated.append(next_tok)

    # Decode
    for step in range(max_new_tokens - 1):
        pos = len(generated) - 1
        x = embed(model, next_tok, pos)
        for i in range(config.n_layer):
            x = forward_layer_decode(i, x, model, disp, kv_cache)
        x = layernorm_cpu(x, model.ln_f_weight, model.ln_f_bias, config.layer_norm_epsilon)
        logits = disp.dispatch('lm_head', x)
        next_tok = int(np.argmax(logits.astype(np.float32)))
        generated.append(next_tok)

    return generated


def main():
    print("=" * 60)
    print("STANDALONE GPT-2 GENERATION — ZERO COREMLTOOLS")
    print("Our compiler → our .hwx → guaranteed ANE")
    print("=" * 60)

    from transformers import GPT2Tokenizer
    tokenizer = GPT2Tokenizer.from_pretrained('openai-community/gpt2')

    print("\n[1] Loading model...")
    model = GPT2Model.from_safetensors(MODEL_PATH)

    print("[2] Compiling with OUR compiler (zero coremltools)...")
    disp = StandaloneDispatcher(model, BUILD_DIR)
    t0 = time.time()
    manifest = disp.compile_all()
    print(f"  {len(disp._ops)} ops compiled in {time.time()-t0:.2f}s")

    print("[3] Starting dispatch pipe...")
    disp.start(manifest)

    # Kill test: "The"
    print("\n[4] Kill test: 'The' → 10 tokens...")
    prompt = tokenizer.encode("The")
    t0 = time.time()
    tokens = generate(model, disp, prompt, max_new_tokens=10)
    elapsed = time.time() - t0
    text = tokenizer.decode(tokens)
    print(f"  Generated: {repr(text)}")
    print(f"  Time: {elapsed:.2f}s ({10/elapsed:.1f} tok/s)")

    # PyTorch reference
    import torch
    from transformers import GPT2LMHeadModel
    pt = GPT2LMHeadModel.from_pretrained('openai-community/gpt2')
    pt.eval()
    with torch.no_grad():
        pt_out = pt.generate(torch.tensor([prompt]), max_new_tokens=10, do_sample=False)
    pt_tokens = pt_out[0].tolist()
    pt_text = tokenizer.decode(pt_tokens)

    match = tokens == pt_tokens
    print(f"\n  PyTorch: {repr(pt_text)}")
    print(f"  Match: {'10/10 EXACT' if match else 'MISMATCH'}")
    if not match:
        for i, (a, b) in enumerate(zip(tokens, pt_tokens)):
            if a != b:
                print(f"    Token {i}: ours={a} ({tokenizer.decode([a])}) vs pt={b} ({tokenizer.decode([b])})")

    # Verify: zero coremltools
    import importlib
    ct_loaded = 'coremltools' in sys.modules
    print(f"\n  coremltools in sys.modules: {ct_loaded}")
    if not ct_loaded:
        print("  *** ZERO COREMLTOOLS CONFIRMED ***")

    disp.stop()

    print(f"\n{'=' * 60}")
    if match and not ct_loaded:
        print("*** STANDALONE GENERATION: PASS ***")
        print("Our compiler, our binaries, guaranteed ANE, 10/10 correct.")
    print("=" * 60)


if __name__ == '__main__':
    main()
